#server:
#    port: 8081
#
server:
  port: 8080
  servlet:
    context-path: /my/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act5?useSSL=false
    username: root
    password: root
    druid:
      db-type: mysql
    #    driver-class-name: org.mariadb.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/

#    process-definition-location-suffixes:
#      - **.bpmn
#      _ **.bpmn20.xml

    history-level: full
  security:
    user:
      name: sa
      password: 123456
      roles: admin
  thymeleaf:
    prefix: classpath:/public
    enabled: true
    encoding: UTF-8
  jpa:
    open-in-view: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
